from .meeting import MEETING_SCRATCHPAD_INST, MEETING_RECAP_INST, MEETING_O1_INST
from .lecture import LECTURE_SCRATCHPAD_INST, LECTURE_RECAP_INST, LECTURE_O1_INST
from .other import OTHER_SCRATCHPAD_INST, OTHER_RECAP_INST, OTHER_O1_INST
from .general_reflection import GENERAL_REFLECTION_INST

__all__ = ["MEETING_SCRATCHPAD_INST", "MEETING_RECAP_INST", "MEETING_O1_INST", "LECTURE_SCRATCHPAD_INST", "LECTURE_RECAP_INST", "LECTURE_O1_INST", "OTHER_SCRATCHPAD_INST", "OTHER_RECAP_INST", "OTHER_O1_INST", "GENERAL_REFLECTION_INST"]
